package com;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

public class FeedbackService {

	public static boolean insertFeedbackData(String name, String email, String rating, String comments) {

		Connection conn = null;
		PreparedStatement pstmt = null;
		boolean isInserted = false;

		try {
			conn = ConnectionFactory.getDBConnection();
			String sql = "insert into feedback(id,name,email,rating,comments) values (?,?,?,?,?) ";
			pstmt = conn.prepareStatement(sql);
			pstmt.setInt(1, autogeneratedId());
			pstmt.setString(2, name);
			pstmt.setString(3, email);
			pstmt.setString(4, rating);
			pstmt.setString(5, comments);
			pstmt.execute();
			isInserted = true;

		} catch (SQLException e) {
			System.out.println("Exception Occured" + e.getMessage());
			e.printStackTrace();
		}
		return isInserted;
	}

	public static int autogeneratedId() {

		int id = 0;

		Connection conn = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {
			conn = ConnectionFactory.getDBConnection();

			String sql = "select max(id) from feedback";
			pstmt = conn.prepareStatement(sql);
			rs = pstmt.executeQuery();
			while (rs.next()) {
				id = rs.getInt(1);
				id = id + 1;
			}

		} catch (Exception e) {
			System.out.println("Exception Occured" + e.getMessage());
			e.printStackTrace();
		}

		return id;
	}

	public static ArrayList<Feedback> getAllFeedbackData() {
		ArrayList<Feedback> feeedbackList = new ArrayList<Feedback>();

		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		try {

			con = ConnectionFactory.getDBConnection();
			String sql = "select * from feedback";
			pstmt = con.prepareStatement(sql);
			rs = pstmt.executeQuery();
			while (rs.next()) {
				Feedback fb = new Feedback();
				fb.setName(rs.getString("name"));
				fb.setEmail(rs.getString("email"));
				fb.setRating(rs.getString("rating"));
				fb.setComments(rs.getString("comments"));
				feeedbackList.add(fb);

			}

		} catch (Exception e) {
			System.out.println("Exception Message:" + e.getMessage());
		}
		return feeedbackList;

	}

	public static Feedback getDataForSelectedId(int id) {

		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		Feedback fb = null;
		try {

			con = ConnectionFactory.getDBConnection();
			String sql = "SELECT * FROM feedback WHERE id = ?";
			pstmt = con.prepareStatement(sql);
			pstmt.setInt(1, id);
			rs = pstmt.executeQuery();

			if (rs.next()) {
				fb = new Feedback();
				fb.setName(rs.getString("name"));
				fb.setEmail(rs.getString("email"));
				fb.setRating(rs.getString("rating"));
				fb.setComments(rs.getString("comments"));
				return fb;
			}

		}

		catch (Exception e) {
			System.out.println("Exception Message:" + e.getMessage());
		}

		return fb;
	}

	public static ArrayList<Integer> getAllDataById() {

		ArrayList<Integer> fid = new ArrayList<Integer>();

		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {

			con = ConnectionFactory.getDBConnection();
			String sql = "SELECT id FROM feedback ORDER BY id ";
			pstmt = con.prepareStatement(sql);
			rs = pstmt.executeQuery();

			while (rs.next()) {
				int id = rs.getInt("id");
				fid.add(id);

			}

		} catch (SQLException e) {
			System.out.println("Exception Message:" + e.getMessage());
		}
		return fid;
	}

	public static boolean updateFeedbackDetailsById(int id, String name, String email, int rating, String comments) {
		Connection con = null;
		PreparedStatement pstmt = null;
		boolean isUpdated = false;

		try {
			con = ConnectionFactory.getDBConnection();
			String sql = "UPDATE feedback SET name = ?, email = ?, rating = ?, comments = ? WHERE id = ?";
			pstmt = con.prepareStatement(sql);
			pstmt.setString(1, name);
			pstmt.setString(2, email);
			pstmt.setInt(3, rating);
			pstmt.setString(4, comments);
			pstmt.setInt(5, id);

			int rowsUpdated = pstmt.executeUpdate();

			if (rowsUpdated > 0) {
				isUpdated = true;
			}

		} catch (SQLException e) {
			System.out.println("Exception Message: " + e.getMessage());
		}
		return isUpdated;

	}

	public static boolean deleteDataById(int id) {
		Connection con = null;
		PreparedStatement pstmt = null;
		boolean isdeleted = false;
		try {
			con = ConnectionFactory.getDBConnection();
			String sql = "delete from feedback where id= ?";
			pstmt = con.prepareStatement(sql);
			pstmt.setInt(1, id);
			int temp = pstmt.executeUpdate();
			isdeleted = temp > 0;
			if (temp > 0) {
				System.out.println("Data Deleted");
			} else {
				System.out.println("Unable to Delete the Data");
			}

		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		return isdeleted;
	}

	public static void main(String ss[]) {
		System.out.println(new FeedbackService().autogeneratedId());

		System.out.println(new FeedbackService().getDataForSelectedId(1));
	}

}
