package com;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

public class FeedbackService2 {

public static boolean insertFeedbackData(String name, String email, String rating, String comments) {

Connection conn = null;
		PreparedStatement pstmt = null;
		boolean isInserted = false;

		try {
			conn = ConnectionFactory.getDBConnection();
			String sql = "insert into feedback(id,name,email,rating,comments) values (?,?,?,?,?) ";
			pstmt = conn.prepareStatement(sql);
			pstmt.setInt(1, autogeneratedId());
			pstmt.setString(2, name);
			pstmt.setString(3, email);
			pstmt.setString(4, rating);
			pstmt.setString(5, comments);
			pstmt.execute();
			isInserted = true;

		} catch (SQLException e) {
			System.out.println("Exception Occured" + e.getMessage());
			e.printStackTrace();
		}
		return isInserted;
	}

}



}